### PR TITLE
Add a simple README.md file

### PR DESCRIPTION
**Pull request by GambitLeBeau**
Adding a README file that was missing for the project.

### CODE REVIEW

**Comment by xicemanx20** [comment]
zeesentence
Thanks for the feedback! There are a few things I noticed during a code review that I think should be added. For example, this sentence is missing a period at the end.

**Comment by xicemanx20** [comment]
zeexample
This is cool, but please add a couple more examples.

**Review by xicemanx20 — CHANGES_REQUESTED** [review]
zeesentence
Thanks for the feedback! There are a few things I noticed during a code review that I think should be added. For example, this sentence is missing a period at the end.

**Review by xicemanx20 — CHANGES_REQUESTED** [review]
zeet##
Please make this ## so it's a smaller title.

**Review by xicemanx20 — CHANGES_REQUESTED** [review]
zeexample
This is cool, but please add a couple more examples.

**Comment by GambitLeBeau** [comment]
All changes requested have been resolved. Please feel free to review the updated changes.

**Pull request merged**
